server:
  port: 8005
  servlet:
    context-path: /api
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: springboot
    key-store-type: pkcs12
    key-alias: springboot
    key-password: springboot

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3307/the_one
    username: root
    password: "07310731"
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
